### ISSUE TITLE
Not Working on Ubuntu 21.10

### ISSUE THREAD

**Issue by dotdwebo** [imperviousinc/fingertip#18]
The GUI doesnt work (There is no response after clicking the file)

This is the error:
**(Fingertip-v0.0.3.AppImage:106896): GLib-GIO-ERROR **: 16:49:20.056: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
SIGTRAP: trace trap
PC=0x7fb55af7e66f m=0 sigcode=128)**

**Comment by dotdwebo** [comment]
i've just tried PR #14 and it keeps showing error.. these are the messages:

`(Fingertip-2da1ee0-x86_64.AppImage:14020): Gtk-WARNING **: 05:40:19.718: Theme parsing error: gtk.css:1412:23: 'font-feature-settings' is not a valid property name

(Fingertip-2da1ee0-x86_64.AppImage:14020): Gtk-WARNING **: 05:40:19.723: Theme parsing error: gtk.css:3324:25: 'font-feature-settings' is not a valid property name

(Fingertip-2da1ee0-x86_64.AppImage:14020): Gtk-WARNING **: 05:40:19.724: Theme parsing error: gtk.css:3786:23: 'font-feature-settings' is not a valid property name
**
GdkPixbuf:ERROR:../gdk-pixbuf/io-ico.c:566:gdk_pixbuf__ico_image_begin_load: assertion failed: (size_func != NULL)
Bail out! GdkPixbuf:ERROR:../gdk-pixbuf/io-ico.c:566:gdk_pixbuf__ico_image_begin_load: assertion failed: (size_func != NULL)
SIGABRT: abort
PC=0x7f798fb28828 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8ef4b0, 0xc00050be80)
	runtime/cgocall.go:156 +0x5c fp=0xc00050be58 sp=0xc00050be20 pc=0x4073dc
github.com/getlantern/systray._Cfunc_nativeLoop()
	_cgo_gotypes.go:120 +0x48 fp=0xc00050be80 sp=0xc00050be58 pc=0x8ea648
github.com/getlantern/systray.nativeLoop(...)
	github.com/getlantern/systray@v1.1.0/systray_nonwindows.go:23
github.com/getlantern/systray.Run(0x8f0d180, 0xc0005043c0)
	github.com/getlantern/systray@v1.1.0/systray.go:78 +0x1f fp=0xc00050bea0 sp=0xc00050be80 pc=0x8e987f
fingertip/internal/ui.Loop(...)
	fingertip/internal/ui/tray.go:23
main.main()
	fingertip/main.go:297 +0x76c fp=0xc00050bf80 sp=0xc00050bea0 pc=0x8ed44c
runtime.main()
	runtime/proc.go:255 +0x227 fp=0xc00050bfe0 sp=0xc00050bf80 pc=0x43b7c7
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00050bfe8 sp=0xc00050bfe0 pc=0x469461

goroutine 6 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00006cb40, 0x0)
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0x49
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0x16f

goroutine 7 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc00006cb40, 0xc00006cae0)
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x5a
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x1c8

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f7962c93870, 0x72)
	runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00030e060, 0xc000308000, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00030e060, {0xc000308000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:32
os.(*File).Read(0xc0001e4010, {0xc000308000, 0x7f7962c93788, 0xc0001e4018})
	os/file.go:119 +0x5e
bufio.(*Scanner).Scan(0xc0001d8ed8)
	bufio/scan.go:215 +0x865
fingertip/internal/resolvers/proc.(*HNSProc).monitor(0xc000134000, {0xac9e20, 0xc0001e4010}, 0x6)
	fingertip/internal/resolvers/proc/hns.go:75 +0xab
fingertip/internal/resolvers/proc.(*HNSProc).goStart.func1()
	fingertip/internal/resolvers/proc/hns.go:66 +0x170
created by fingertip/internal/resolvers/proc.(*HNSProc).goStart
	fingertip/internal/resolvers/proc/hns.go:50 +0x77

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f7962c936a0, 0x72)
	runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000506080, 0x4, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000506080)
	internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc000506080)
	net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc000534000)
	net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc000534000)
	net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc00017e0e0, {0xaca6f0, 0xc000534000})
	net/http/server.go:3002 +0x394
net/http.(*Server).ListenAndServe(0xc00017e0e0)
	net/http/server.go:2931 +0x7d
main.(*App).listen(...)
	fingertip/main.go:355
main.main.func1.1()
	fingertip/main.go:162 +0x2a
created by main.main.func1
	fingertip/main.go:161 +0xbe

goroutine 11 [select]:
main.main.func5()
	fingertip/main.go:214 +0xfc
created by main.main
	fingertip/main.go:212 +0x645

goroutine 25 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x36da, 0xc000055cf8, 0x1000004, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc0001fe060)
	os/wait_waitid.go:33 +0x9c
os.(*Process).wait(0xc0001fe060)
	os/exec_unix.go:23 +0x28
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc0000e8000)
	os/exec/exec.go:507 +0x54
os/exec.(*Cmd).Run(0x9fbd66)
	os/exec/exec.go:341 +0x39
github.com/pkg/browser.runCmd({0x9fbd66, 0x6}, {0xc000055f18, 0xc0000b0020, 0xc0000b0035})
	github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser.go:56 +0x85
github.com/pkg/browser.openBrowser({0xc0000b0020, 0x1b})
	github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser_linux.go:16 +0x1bb
github.com/pkg/browser.OpenURL(...)
	github.com/pkg/browser@v0.0.0-20210706143420-7d21f8c997e2/browser.go:49
main.autoConfigure(0x9834418b35f0c5f9, 0xac, 0x2d)
	fingertip/main.go:73 +0x38
main.main.func1.2()
	fingertip/main.go:170 +0x3c
created by main.main.func1
	fingertip/main.go:165 +0x117

goroutine 26 [select]:
fingertip/internal/ui.(*State).initMenu.func1()
	fingertip/internal/ui/tray.go:144 +0xb4
created by fingertip/internal/ui.(*State).initMenu
	fingertip/internal/ui/tray.go:142 +0x2af

rax    0x0
rbx    0x7f798a2ac080
rcx    0x7f798fb28828
rdx    0xffffffe6
rdi    0x36c4
rsi    0x6
rbp    0x6
rsp    0x7fff22e3e440
r8     0x7fff22e3e510
r9     0x0
r10    0x8
r11    0x246
r12    0x73
r13    0x16
r14    0x7f796001b3e0
r15    0x7f796001b3e0
rip    0x7f798fb28828
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
`

**Comment by dotdwebo** [comment]
another error message:

`[14118:14118:0303/054025.050000:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
mkdir: cannot create directory '/run/user/0': Permission denied
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0
/usr/bin/xdg-open: 869: iceweasel: not found
/usr/bin/xdg-open: 869: seamonkey: not found
/usr/bin/xdg-open: 869: mozilla: not found
/usr/bin/xdg-open: 869: epiphany: not found
/usr/bin/xdg-open: 869: konqueror: not found
/usr/bin/xdg-open: 869: chromium: not found
/usr/bin/xdg-open: 869: chromium-browser: not found
[14266:14266:0303/054034.083045:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'http://127.0.0.1:9590/setup'
`

**Comment by buffrr** [comment]
I tried this on a VM with Ubuntu 21.10 and Fingertip worked with PR 14. I can only see the first three warnings but it worked fine. Are you running Fingertip as root by any chance? I only got those error messages when I tried to run it that way (running it as root isn't recommended)

**Comment by dotdwebo** [comment]
i tried to run it as common user (not root).. 
maybe using version 21.10 (which is not LTS) is not recommended enough?

I'm planning to downgrade to version 20.04 (LTS)

**Comment by dotdwebo** [comment]
It works on Ubuntu 20.04 (LTS)!

**Comment by buffrr** [comment]
That's good to know. I can't seem to reproduce this issue on Ubuntu 21.10 VM either but let's keep it open for now because I want to try it installed on a machine just to make sure. 

> maybe using version 21.10 (which is not LTS) is not recommended enough?

yeah, it's usually a good idea to go with the LTS version it's more stable.
