### ISSUE TITLE
Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

### ISSUE THREAD

**Issue by paveloom** [imperviousinc/fingertip#7]
Here's what I get when trying to run the AppImage on Fedora 34:

<details>
<summary>Backtrace</summary>
<pre><code>
(Fingertip-v0.0.3.AppImage:78150): GLib-GIO-ERROR **: 10:52:21.783: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
SIGTRAP: trace trap
PC=0x7f8888e74f7f m=0 sigcode=128
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8ef5b0, 0xc000173e58)
	runtime/cgocall.go:156 +0x5c fp=0xc000173e30 sp=0xc000173df8 pc=0x4073dc
github.com/getlantern/systray._Cfunc_registerSystray()
	_cgo_gotypes.go:144 +0x45 fp=0xc000173e58 sp=0xc000173e30 pc=0x8ea7c5
github.com/getlantern/systray.registerSystray(...)
	github.com/getlantern/systray@v1.1.0/systray_nonwindows.go:19
github.com/getlantern/systray.Register(0xc000498020, 0xc000498010)
	github.com/getlantern/systray@v1.1.0/systray.go:106 +0x14b fp=0xc000173e80 sp=0xc000173e58 pc=0x8e9acb
github.com/getlantern/systray.Run(0x8f0d180, 0xc000288ae0)
	github.com/getlantern/systray@v1.1.0/systray.go:77 +0x19 fp=0xc000173ea0 sp=0xc000173e80 pc=0x8e9939
fingertip/internal/ui.Loop(...)
	fingertip/internal/ui/tray.go:23
main.main()
	fingertip/main.go:297 +0x76c fp=0xc000173f80 sp=0xc000173ea0 pc=0x8ed50c
runtime.main()
	runtime/proc.go:255 +0x227 fp=0xc000173fe0 sp=0xc000173f80 pc=0x43b7c7
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000173fe8 sp=0xc000173fe0 pc=0x469401

goroutine 6 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000070b40, 0x0)
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0x49
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0x16f

goroutine 7 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000070b40, 0xc000070ae0)
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x5a
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x1c8

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f885c080870, 0x72)
	runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000324080, 0xc000328000, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000324080, {0xc000328000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000324080, {0xc000328000, 0x7f885c037ed8, 0x59})
	net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0001ee028, {0xc000328000, 0x7f885c037e01, 0xc0001ee028})
	net/net.go:183 +0x45
github.com/miekg/dns.(*Conn).Read(0xc0001da090, {0xc000328000, 0xc0001ee028, 0x1083240})
	github.com/miekg/dns@v1.1.31/client.go:276 +0x149
github.com/miekg/dns.(*Conn).ReadMsgHeader(0xc0001da090, 0x0)
	github.com/miekg/dns@v1.1.31/client.go:240 +0xbf
github.com/miekg/dns.(*Conn).ReadMsg(0xc0001da090)
	github.com/miekg/dns@v1.1.31/client.go:202 +0x27
github.com/miekg/dns.(*Client).exchange(0x1002340, 0xc0001d7f10, 0xc0001da090)
	github.com/miekg/dns@v1.1.31/client.go:188 +0x18d
github.com/miekg/dns.(*Client).ExchangeWithConn.func1()
	github.com/miekg/dns@v1.1.31/client.go:158 +0x25
github.com/miekg/dns.(*singleflight).Do(0x1002398, {0xc0001e81a0, 0xc}, 0xc0001d7d30)
	github.com/miekg/dns@v1.1.31/singleinflight.go:51 +0x19a
github.com/miekg/dns.(*Client).ExchangeWithConn(0x1002340, 0xc0001d7f10, 0xc0001da090)
	github.com/miekg/dns@v1.1.31/client.go:157 +0x177
github.com/miekg/dns.(*Client).Exchange(0x99e060, 0xc0001e8001, {0xa08ded, 0x644438})
	github.com/miekg/dns@v1.1.31/client.go:135 +0xe9
fingertip/internal/config.exchangeWithRetry(0xc0001d7f10, {0xc0001d7ee0, 0x3, 0x1})
	fingertip/internal/config/debug.go:114 +0xb4
fingertip/internal/config.testDNSInterference()
	fingertip/internal/config/debug.go:74 +0x1c5
fingertip/internal/config.(*Debugger).NewProbe.func1()
	fingertip/internal/config/debug.go:168 +0x26
created by fingertip/internal/config.(*Debugger).NewProbe
	fingertip/internal/config/debug.go:167 +0xb5

goroutine 11 [select]:
main.main.func5()
	fingertip/main.go:214 +0xfc
created by main.main
	fingertip/main.go:212 +0x645

goroutine 12 [chan receive]:
github.com/getlantern/systray.Register.func2()
	github.com/getlantern/systray@v1.1.0/systray.go:93 +0x28
created by github.com/getlantern/systray.Register
	github.com/getlantern/systray@v1.1.0/systray.go:92 +0xc8

rax    0x0
rbx    0x1
rcx    0x1
rdx    0x7f8883698a00
rdi    0x7
rsi    0x7f8888e140a0
rbp    0x0
rsp    0x7ffd18d73590
r8     0x0
r9     0x7f8888db04e0
r10    0x7f8888db03e0
r11    0x293
r12    0x4
r13    0x7ffd18d735e0
r14    0x7f8888f51d40
r15    0x7f8888f51db0
rip    0x7f8888e74f7f
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
</code></pre>
</details>

**Comment by thekidconnect** [comment]
was this issue ever fixed?
